project:
  type: book
  output-dir: docs

book:
  title: "nextflow"
  author: "Sowmya Parthiban"
  date: "10/13/2024"
  chapters:
    - index.qmd
    - processes.qmd
    - more_python_commands.qmd
    - running_scripts_in_sequence.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    copy-code: true
  pdf:
    documentclass: scrreprt

editor: visual

